### ISSUE TITLE
call a script

### ISSUE THREAD

**Issue by vMeph** [originallyus/node-red-contrib-alexa-local#82]
how can i call a script?
exemple
```
script:
  test:
    sequence:
      - service: media_player.alexa_tts
        entity_id: media_player.echo_dot
        data_template:
          message: Right now, it is {{ states('sensor.time') }}o´clock
```
so i set a local alexa node and then what type of node do i need?
and then i would call it by saying alexa turn on test?
